POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "How to Create and Test a Node.js Blog API",
    "author": "Ben Merchant",
    "url": "https://medium.com/@benmerchant/how-to-create-and-test-a-node-js-blog-api-819170280abd",
    "likes": 60
}