POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYwYWQyN2I2ODAyZDY4NTc1Y2E5ZDNhNiIsImlhdCI6MTYyMTk3MDA2NywiZXhwIjoxNjIxOTczNjY3fQ.k1nrv1NepIM2MqLca_UTQlFrmpHISDLyqu_v6xYXpII

{
    "title": "Testing Again",
    "author": "Admin",
    "url": "http://localhost:3001/api/blogs",
    "likes": 1
}