DELETE http://localhost:3001/api/blogs/60ad335196a3cf0b5ca19c0b
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYwYWQyN2I2ODAyZDY4NTc1Y2E5ZDNhNiIsImlhdCI6MTYyMTk2NDg0NywiZXhwIjoxNjIxOTY4NDQ3fQ.NxxOZeNIt8Wh7HJ38yX2SjKYyM6oX_9UpMFKsi-yDIM